# Generated by Django 4.2.18 on 2025-01-22 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='city',
            new_name='course',
        ),
    ]
